site_name: Navigation test
site_description: Nav test
theme: readthedocs
repo_url: https://github.com/ajitchelat/ghpages_test
markdown_extensions:
  - admonition
  - codehilite
  - toc:
     anchorlink: True

pages:
- Home: index.md
- User Guide:
    - Writing your docs: index.md
- About:
    - License: index.md
    - Release Notes:
      - Version 1: index.md
      - Version 2: index.md
      - Version 3: index.md
      - Release Notes:
        - Version 1: index.md
        - Version 2: index.md
        - Version 3: index.md
        - Release Notes:
          - Version 1: index.md
          - Version 2: index.md
          - Version 3: index.md
